name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps (core + dev)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/core.txt -r requirements/dev.txt

      - name: Generate synthetic data & fast-train RF
        run: |
          python tools/generate_synthetic_data.py --n 3000
          python training/train.py --train data/transactions_mock.csv --out app/model_sklearn.pkl --model rf --val-size 0.2 --seed 7
      - name: Build gazetteer
        run: python tools/build_gazetteer.py --csv data/gazetteer_merchants.csv --out app/gazetteer.pkl

      - name: Lint & tests
        run: |
          ruff check .
          black --check .
          pytest -q

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: bridgelite:ci
          load: true

      - name: Smoke run
        run: |
          docker run -d --rm -p 8000:8000 --name bridgelite-ci bridgelite:ci
          # give it a few seconds to boot
          sleep 5
          curl -fsS http://127.0.0.1:8000/health
          docker logs bridgelite-ci --tail 50
          docker rm -f bridgelite-ci
